COMPRESS = Huff/Compress.c
DESCOMPRESS = Huff/Descompress.c
BINARY_TREE = Estruturas/HuffmanTree.c
HASH = Estruturas/HuffmanHash.c
HEAP = Estruturas/HuffmanHeap.c
MAIN = Huff/Main.c

compile_huffman:
	gcc $(COMPRESS) $(HUFFMAN) $(BINARY_TREE) $(HASH) $(HEAP) $(MAIN) -o huffman